---
- name: Install Zabbix Agent
  apt:
    deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix/zabbix-agent_5.0.4-1%2Bbionic_amd64.deb
  notify: "Restart Zabbix Agent Service"

- name: Configure Zabbix Agent Configuration File
  template:
    src: zabbix_agentd.conf.org.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: "0644"
  notify: "Restart Zabbix Agent Service"